/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_oscim_utils_TessJNI */

#ifndef _Included_org_oscim_utils_TessJNI
#define _Included_org_oscim_utils_TessJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    newTess
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_oscim_utils_TessJNI_newTess
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    freeTess
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_oscim_utils_TessJNI_freeTess
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    addContour
 * Signature: (JI[FIII)V
 */
JNIEXPORT void JNICALL Java_org_oscim_utils_TessJNI_addContour
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jint, jint, jint);

/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    addMultiContour2D
 * Signature: (J[I[FII)V
 */
JNIEXPORT void JNICALL Java_org_oscim_utils_TessJNI_addMultiContour2D
  (JNIEnv *, jclass, jlong, jintArray, jfloatArray, jint, jint);

/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    tessContour2D
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_org_oscim_utils_TessJNI_tessContour2D
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    getVertexCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_oscim_utils_TessJNI_getVertexCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    getVertices
 * Signature: (J[FII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_oscim_utils_TessJNI_getVertices
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint);

/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    getVerticesS
 * Signature: (J[SIIF)V
 */
JNIEXPORT void JNICALL Java_org_oscim_utils_TessJNI_getVerticesS
  (JNIEnv *, jclass, jlong, jshortArray, jint, jint, jfloat);

/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    getVertexIndices
 * Signature: (J[III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_oscim_utils_TessJNI_getVertexIndices
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    getElementCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_oscim_utils_TessJNI_getElementCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    getElements
 * Signature: (J[III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_oscim_utils_TessJNI_getElements
  (JNIEnv *, jclass, jlong, jintArray, jint, jint);

/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    getElementsS
 * Signature: (J[SII)V
 */
JNIEXPORT void JNICALL Java_org_oscim_utils_TessJNI_getElementsS
  (JNIEnv *, jclass, jlong, jshortArray, jint, jint);

/*
 * Class:     org_oscim_utils_TessJNI
 * Method:    getElementsWithInputVertexIds
 * Signature: (J[SIII)V
 */
JNIEXPORT void JNICALL Java_org_oscim_utils_TessJNI_getElementsWithInputVertexIds
  (JNIEnv *, jclass, jlong, jshortArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
